const ActionType = {
    LOAD_USER: "LOAD_USER",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    UPDATE_GEO_DATA: "UPDATE_GEO_DATA",
    UPDATE_POSITION: "UPDATE_POSITION",
    LOAD_ELEVATION: "LOAD_ELEVATION",
    LOAD_SAFETY_ALTITUDE_LEVEL: "LOAD_SAFETY_ALTITUDE_LEVEL",
    DOWNLOAD_REPORT: "DOWNLOAD_REPORT",
    SWITCH_LANGUAGE: "SWITCH_LANGUAGE",
    TOGGLE_CADASTER: "TOGGLE_CADASTER",
    RESOLVE_POSITION_FROM_CADASTER: "RESOLVE_POSITION_FROM_CADASTER",
    RESET_ELEVATION_AND_SAFETY_LEVEL: "RESET_ELEVATION_AND_SAFETY_LEVEL",
    PUBLISH_MESSAGE: "PUBLISH_MESSAGE",
    DISMISS_MESSAGE: "DISMISS_MESSAGE"
};

export const AsyncStatus = {
    REQUEST: 0,
    SUCCESS: 1,
    FAILURE: 2
};

export default ActionType;
